version: '3'

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"

  vk_bot:
    build: ./vk_bot
    env_file:
      - .env

  tg_bot:
    build: ./tg_bot
    env_file:
      - .env
